### ISSUE TITLE
需要安装 firefox 浏览器么

### ISSUE THREAD

**Issue by banduoba** [lifetyper/alipay_fetcher#2]
你好,请问需要安装 Firefox 浏览器么 一直报错运行
```bash
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    fetcher.run()
  File "/Users/meng/Documents/workspace/alipay_fetcher/alipay_fetcher.py", line 169, in run
    self.login_with_firefox()
  File "/Users/meng/Documents/workspace/alipay_fetcher/alipay_fetcher.py", line 51, in login_with_firefox
    driver = webdriver.Firefox(firefox_options=options)
  File "/Users/meng/.local/share/virtualenvs/alipay_fetcher-Jg8vV-uo/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/Users/meng/.local/share/virtualenvs/alipay_fetcher-Jg8vV-uo/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/meng/.local/share/virtualenvs/alipay_fetcher-Jg8vV-uo/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/meng/.local/share/virtualenvs/alipay_fetcher-Jg8vV-uo/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/meng/.local/share/virtualenvs/alipay_fetcher-Jg8vV-uo/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```

**Comment by lifetyper** [comment]
当然要。。。

**Comment by banduoba** [comment]
> 当然要。。。
请问终端输出的这个提示是什么意思呢?目前这个获取的账单没有输出是吧
![image](https://user-images.githubusercontent.com/4811366/53137730-bd730180-35be-11e9-8eb6-f278da294e26.png)

**Comment by lifetyper** [comment]
你这个是没有登录成功，在登陆后加一行：
driver.save_screenshot(self.screen_shot)
看看截图里爆的什么错

**Comment by banduoba** [comment]
> 你这个是没有登录成功，在登陆后加一行：
> driver.save_screenshot(self.screen_shot)
> 看看截图里爆的什么错

是加在`login_with_firefox`这个方法里面下面的位置么
```python
sleep(random_time(0.2, 0.6))
        login_btn = driver.find_element_by_id('J-login-btn')
        login_btn.click()
        driver.save_screenshot(self.screen_shot)
```

**Comment by lifetyper** [comment]
login_btn = driver.find_element_by_id('J-login-btn')
        login_btn.click()

sleep(random_time(0.7, 1.3))
driver.save_screenshot(self.screen_shot)

放在这个sleep后面

**Comment by banduoba** [comment]
> ```
>     login_btn = driver.find_element_by_id('J-login-btn')
>     login_btn.click()
> ```
> sleep(random_time(0.7, 1.3))
> driver.save_screenshot(self.screen_shot)
> 
> 放在这个sleep后面

终于看到错误原因了这么操作,原来是账号错了,谢谢啊

**Comment by banduoba** [comment]
日志里面的这些 warn 需要处理么
```bash
1550719656676   mozrunner::runner       INFO    Running command: "/Applications/Firefox.app/Contents/MacOS/firefox-bin" "-marionette" "-headless" "-foreground" "-no-remote" "-profile" "
/var/folders/rq/h_nt1mrd1fs0tl58hq3lrxkc0000gn/T/rust_mozprofile.VqXbWRFT0DIL"
*** You are running in headless mode.
1550719657076   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: resource://pdf.js/
1550719657076   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: about:reader*
1550719658379   Marionette      INFO    Listening on port 56203
1550719658424   Marionette      WARN    TLS certificate errors will be ignored for this session
1550719679805   Marionette      INFO    Stopped listening on port 56203
```

**Comment by lifetyper** [comment]
不影响使用就不用管了。
